base_locale: es
locales: [en, es, ca]
data:
  read:
    - config/locales/**/%{locale}.yml
    - config/locales/**/*/%{locale}.yml
    - vendor/auth_strategies/**/config/locales/**/%{locale}.yml
    - vendor/auth_strategies/**/config/locales/**/*/%{locale}.yml
search:
  paths:
    - app/
    - vendor/auth_strategies/
  relative_roots:
    - app/controllers
    - app/helpers
    - app/mailers
    - app/presenters
    - app/views
    - vendor/auth_strategies/null_strategy/app/views
ignore_missing:
  - 'gobierto_budgets.visualizations.*'
  - 'layouts.sandbox.*'
  - 'sandbox.*'
  - 'gobierto_budget_consultations.consultation_statuses.*'
  - 'gobierto_observatory.cards.*'
  - 'gobierto_budgets.budgets.cards.*'
  - 'gobierto_budgets.budgets.index_old.*'
  - 'gobierto_budgets.budgets.guide.*'
  - 'gobierto_budgets.invoices.show.table.fields.*'

ignore_unused:
  - 'number.*'
  - 'time.*'
  - 'errors.*'
  - 'datetime.*'
  - 'date.*'
  - 'activerecord.*'
  - 'activemodel.*'
  - 'helpers.*'
  - 'support.*'
  - 'layouts.sandbox.*'
  - 'layouts.*.application.*'
  - 'user.subscriptions.create.*_success'
  - 'gobierto_admin.gobierto_budget_consultations.consultations.consultation_items.*_modal.*'
  - 'gobierto_admin.gobierto_participation.shared.navigation.*'
  - 'gobierto_budgets.budget_lines.show.twitter_text_*'
  - 'gobierto_budgets.visualizations.G_custom'
  - 'gobierto_budgets.visualizations.I_custom'
  - 'gobierto_budgets.budgets.index.*'
  - 'gobierto_budgets.budgets_execution.*'
  - 'gobierto_budgets.invoices.show.table.fields.*'
  - 'gobierto_people.activities.gobierto_people_person*'
  - 'invisible_captcha.*'
  - '*.events.*'
  - 'gobierto_budget_consultations.consultation_statuses.*'
  - 'user.census_verifications.messages.not_verified'
  - 'gobierto_budget_consultations.consultation_statuses.*'
  - 'user.sessions.user_not_signed_in'
  - 'gobierto_budget_consultations.consultations.consultation_responses.new.user_not_signed_in_html'
  - 'views.pagination.*'
  - 'helpers.page_entries_info.*'
  - 'gobierto_observatory.cards.*'
  - 'gobierto_budgets.budgets.cards.*'
  - 'gobierto_budgets.budgets.meta.*'
  - 'user.subscriptions.subscribable_button.*'
  - 'gobierto_participation.welcome.index.*'
  - 'gobierto_participation.processes.contribution_containers.show.login_signup_idea'
  - 'gobierto_participation.processes.contribution_containers.show.login_signup_proposal'
  - 'gobierto_participation.processes.contribution_containers.show.login_signup_question'
  - 'gobierto_participation.processes.contribution_containers.show.put_idea'
  - 'gobierto_participation.processes.contribution_containers.show.put_proposal'
  - 'gobierto_participation.processes.contribution_containers.show.put_question'
  - 'gobierto_participation.processes.contribution_containers.show.show_ideas'
  - 'gobierto_participation.processes.contribution_containers.show.show_proposals'
  - 'gobierto_participation.processes.contribution_containers.show.show_questions'
  - 'gobierto_participation.processes.contributions.contribution.values_this_idea'
  - 'gobierto_participation.processes.contributions.contribution.values_this_proposal'
  - 'gobierto_participation.processes.contributions.contribution.values_this_question'
  - 'gobierto_participation.processes.contribution_containers.show.put_idea'
  - 'gobierto_participation.processes.contribution_containers.show.put_proposal'
  - 'gobierto_participation.processes.contribution_containers.show.put_question'
  - 'gobierto_participation.processes.contribution_containers.show.idea.*'
  - 'gobierto_participation.processes.contribution_containers.show.proposal.*'
  - 'gobierto_participation.processes.contribution_containers.show.question.*'
  - 'gobierto_participation.processes.contributions.form.*'
  - 'gobierto_admin.gobierto_participation.processes.edit.*'
  - 'gobierto_admin.gobierto_participation.processes.*.success_*'

translation:
  api_key: ''
